#!/usr/bin/env bash
set -euo pipefail

# Usage: bash scripts/model/model_fetch.sh [7b|70b]
#
# Downloads the model if not already present, then writes
# scripts/model/model_config.sh which is sourced by all other scripts.
# To switch models just re-run this script with the other size.

MODEL_SIZE="${1:-7b}"

MODEL_DIR="${HOME}/model_cache/llama"
mkdir -p "$MODEL_DIR"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/model_config.sh"

case "$MODEL_SIZE" in
  7b)
    MODEL_FILE="${MODEL_DIR}/llama-2-7b.Q4_K_M.gguf"
    MODEL_PATH_IN_CONTAINER="/models/llama-2-7b.Q4_K_M.gguf"
    URL="https://huggingface.co/TheBloke/Llama-2-7B-GGUF/resolve/main/llama-2-7b.Q4_K_M.gguf"
    CTX_SIZE=2048
    CPUSET="0-61"
    RESET_TIMEOUT=90
    HEALTH_RETRIES=30
    HEALTH_SLEEP=2
    REQUEST_TIMEOUT=600
    BASELINE_S=2
    PROC_INTERVAL_S=0.1
    ;;
  70b)
    MODEL_FILE="${MODEL_DIR}/llama-3.1-70b.Q4_K_M.gguf"
    MODEL_PATH_IN_CONTAINER="/models/llama-3.1-70b.Q4_K_M.gguf"
    URL="https://huggingface.co/bartowski/Meta-Llama-3.1-70B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-70B-Instruct-Q4_K_M.gguf"
    CTX_SIZE=2048
    CPUSET="0-61"
    RESET_TIMEOUT=300
    HEALTH_RETRIES=60
    HEALTH_SLEEP=5
    REQUEST_TIMEOUT=3600
    BASELINE_S=5
    PROC_INTERVAL_S=0.1
    ;;
  *)
    echo "Usage: $0 [7b|70b]"
    exit 1
    ;;
esac

# Download only if not already present
if [ -s "$MODEL_FILE" ]; then
  echo "Model already exists: $MODEL_FILE"
  ls -lh "$MODEL_FILE"
else
  if [ -z "${HF_TOKEN:-}" ]; then
    echo "ERROR: HF_TOKEN is not set."
    echo "Set it with: export HF_TOKEN='your_token_here'"
    exit 1
  fi
  echo "Downloading $MODEL_SIZE model to: $MODEL_FILE"
  TMP_FILE="${MODEL_FILE}.part"
  rm -f "$TMP_FILE"
  wget --header="Authorization: Bearer ${HF_TOKEN}" -O "$TMP_FILE" "$URL"
  mv "$TMP_FILE" "$MODEL_FILE"
  echo "Downloaded:"
  ls -lh "$MODEL_FILE"
fi

# Always write config (even if model already existed)
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by model_fetch.sh — do not edit manually.
# Re-run: bash scripts/model/model_fetch.sh [7b|70b]

MODEL_SIZE="${MODEL_SIZE}"
MODEL_FILE="${MODEL_FILE}"
MODEL_PATH_IN_CONTAINER="${MODEL_PATH_IN_CONTAINER}"
MODEL_DIR="${MODEL_DIR}"
CTX_SIZE=${CTX_SIZE}
CPUSET="${CPUSET}"
RESET_TIMEOUT=${RESET_TIMEOUT}
HEALTH_RETRIES=${HEALTH_RETRIES}
HEALTH_SLEEP=${HEALTH_SLEEP}
REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
BASELINE_S=${BASELINE_S}
PROC_INTERVAL_S=${PROC_INTERVAL_S}
EOF

echo ""
echo "Config written: ${CONFIG_FILE}"
echo "  MODEL_SIZE      = ${MODEL_SIZE}"
echo "  REQUEST_TIMEOUT = ${REQUEST_TIMEOUT}s"
echo "  RESET_TIMEOUT   = ${RESET_TIMEOUT}s"
echo "  HEALTH_RETRIES  = ${HEALTH_RETRIES} x ${HEALTH_SLEEP}s"
echo "  BASELINE_S      = ${BASELINE_S}s"
echo ""
echo "All scripts now use the ${MODEL_SIZE} model."
echo "To switch: bash scripts/model/model_fetch.sh [7b|70b]"